--- 
- hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Import variable files
    ansible.builtin.include_vars: vars/vpc_setup
  - name: Import variable files
    ansible.builtin.include_vars: vars/output_vars
  
  - name: create vprofile EC2 key pair 
    amazon.aws.ec2_key:
      name: vprofile-key
      region: us-east-2
    register: key_out

  #- debug: 
      #var: key_out
  
  - name: store private key into file bastion-key.pem
    copy:
      content: "{{key_out.key.private_key}}"
      dest: ./bastion-key.pem
      mode: 0600
    when: key_out.changed

  - name: Create sg for bastion host 
    ec2_group:
      name: Bastion-host-sg
      description: Allow port 22 from every where and all port within sg 
      region: "{{region}}"
      vpc_id: "{{vpcid}}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{MYIP}}"
    register: BastionSG_out

  #- debug:
      #var: BastionSG_out

  - name: Creating Bastion Host 
    amazon.aws.ec2_instance:
      name: "Bastion-host"
      region: "{{region}}"
      key_name: "vprofile-key"
      vpc_subnet_id: "{{pubsub1id}}"
      instance_type: t2.micro
      security_group: "{{BastionSG_out.group_name}}"
      wait: yes
      wait_timeout: 300
      network:
        assign_public_ip: true
      image_id: "{{bastion_ami}}"
      tags:
        Environment: Vprofile
    register: bastionHost_out


  