--- 
- hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Import variable files
    ansible.builtin.include_vars: vars/bastion_setup
  - name: Import variable files
    ansible.builtin.include_vars: vars/output_vars
  
  - name: create vprofile EC2 key pair 
    amazon.aws.ec2_key:
      name: vprofile-key
      region: us-east-2
    register: key_out

  - debug: 
      var: key_out
  
  - name: store private key into file bastion-key.pem
    copy:
      content: "{{key_out.key.private_key}}"
      dest: ./bastion-key.pem
      mode: 0600
    when: key_out.changed

  - name: Create sg for bastion host 
    ec2_group:
      name: Bastion-host-sg
      description: Allow port 22 from every where and all port within sg 
      region: "{{region}}"
      vpc_id: "{{vpcid}}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{MYIP}}"
    register: BastionSG_out

  - name: Create EC2 instance 
    amazon.aws.ec2_instance:
      key_name: vprofile-key
      region: "{{region}}"
      instance_type: t2.micro
      image: "{{bastion_ami}}"
      wait: yes
      wait_timeout: 300
      instance_tags:
        Name: "Bastion_host"
        Project: Vprofile
        Owner: DevOps Team
      exact_count: 1
      count_tag:
        Name: "Bastion_host"
        Project: Vprofile
        Owner: DevOps Team
      group_id: "{{BastionSG_out.group_id}}"
      vpc_subnet_id: "{{pubsub1id}}"
    register: bastionHost_out

  