--- 
- name: Install Java and net-tools
  hosts: nexus_server
  become: yes
  tasks:
  - name: Update apt repo and cache 
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install Java 8
    ansible.builtin.apt: name=openjdk-8-jre-headless
  - name: Install net-tools
    ansible.builtin.apt: name=net-tools

- name: Download and unpack nexus folder
  hosts: nexus_server
  become: yes
  tasks:
  - name: Check nexus folder stats
    ansible.builtin.stat:
      path: /opt/nexus
    register: stat_result
  #- debug: msg={{stat_result}}
  - name: Download nexus
    ansible.builtin.get_url:
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /opt/
    register: download_result
  #- ansible.builtin.debug: msg={{ download_result }}
  - name: Untar nexus installer
    ansible.builtin.unarchive:
      src: "{{ download_result.dest }}"
      dest: /opt/
      remote_src: yes
    when: not stat_result.stat.exists
  - name: Find nexus folder
    ansible.builtin.find:
      paths: /opt/
      patterns: "nexus-*"
      file_type: directory
    register: find_result
  #- ansible.builtin.debug: msg={{ find_result }}
  - name: Rename nexus folder
    ansible.builtin.shell: mv {{ find_result.files[0].path }} /opt/nexus
    when: not stat_result.stat.exists

- name: Create nexus user to own nexus folder
  hosts: nexus_server
  become: yes
  tasks:
  - name: Ensure group nexus exists 
    ansible.builtin.group:
      name: nexus
      state: present
  - name: Create nexus user
    ansible.builtin.user:
      name: nexus
      group: nexus
  - name: Make nexus user owner of nexus folder
    ansible.builtin.file:
      path: /opt/nexus
      state: directory
      recurse: yes
      owner: nexus
      group: nexus
  - name: Make nexus user owner of sonatype-work folder
    ansible.builtin.file:
      path: /opt/sonatype-work
      state: directory
      recurse: yes
      owner: nexus
      group: nexus
    
- name: Start nexus service
  hosts: nexus_server
  become: yes
  tasks:
  - name: Set run_as_user nexus 
    ansible.builtin.lineinfile:
      path: /opt/nexus/bin/nexus.rc
      regexp: '^#run_as_user=""'
      line: run_as_user="nexus"
  - name: Start nexus
    ansible.builtin.command: /opt/nexus/bin/nexus start
