--- 
- name: Install Java and net-tools
  hosts: nexus_server
  become: yes
  tasks:
  - name: Update apt repo and cache 
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install Java 8
    ansible.builtin.apt: name=openjdk-8-jre-headless
  - name: Install net-tools
    ansible.builtin.apt: name=net-tools