--- 
- name: Install node and npm
  hosts: 18.191.144.58
  become: true
  tasks:
  - name: Update apt repo and cache 
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    ansible.builtin.apt:
      pkg:
      - nodejs
      - npm

- name: Deploy Nodejs app
  hosts: 18.191.144.58
  become: true
  tasks:
  - name: Copy nodejs folder to server
    ansible.builtin.copy:
      src: /home/ubuntu/ansible/simple-nodejs/nodejs-app-1.0.0.tgz
      dest: /home/ubuntu/app-1.0.0.tgz
  - name: Unpack the nodejs file
    ansible.builtin.unarchive:
      src: /home/ubuntu/app-1.0.0.tgz
      dest: /home/ubuntu/
      remote_src: yes

