--- 
- name: Install node and npm
  hosts: 18.191.144.58
  become: true
  tasks:
  - name: Update apt repo and cache 
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    ansible.builtin.apt:
      pkg:
      - nodejs
      - npm

- name: Deploy Nodejs app
  hosts: 18.191.144.58
  become: true
  tasks:
  - name: Unpack the nodejs file
    ansible.builtin.unarchive:
      src: /home/ubuntu/ansible/simple-nodejs/nodejs-app-1.0.0.tgz
      dest: /home/ubuntu/
  - name: Install dependencies
    community.general.npm:
      path: /home/ubuntu/package
  - name: Start the application
    ansible.builtin.command:
      chdir: /home/ubuntu/package/app
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    ansible.builtin.shell: ps aux | grep node
    register: app_status
  - ansible.builtin.debug: msg={{ app_status.stdout_lines }}



