--- 
- hosts: 3.19.188.156
  become: yes
  tasks:
  - name: Install git
    ansible.builtin.apt:
      name: git
      state: present
    
  - name: Install tree
    ansible.builtin.apt:
      name: tree
      statee: present
    ignore_errors: True
    
  - name: Install wget
    ansible.builtin.apt:
      name: wget
      state: present
    
