--- 
- hosts: 3.19.188.156
  become: yes
  tasks:
  - ansible.builtin.include_tasks:
      file: myfile.yaml
  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: present