--- 
- hosts: 18.222.92.184
  become: yes
  tasks:
  - ansible.builtin.include_tasks:
      file: myfile.yaml
  
  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: present
  - name: copy index.html
    ansible.builtin.copy:
      src: /home/ubuntu/ansible/index.html
      dest: /var/www/html
    notify:
      - Restart apache
  - name: copy index.html
    ansible.builtin.copy:
      src: /home/ubuntu/ansible/coffee.jpg
      dest: /var/www/html
    notify:
      - Restart apache

  handlers:
  - name: Restart apache
    ansible.builtin.service:
      name: apache2
      state: restarted