--- 
- name: Create key pair 
  hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: create EC2 key pair 
    amazon.aws.ec2_key:
      name: sample
      region: us-east-2
    register: keyout

  - debug: msg={{keyout}}