--- 
- hosts: 3.145.148.37
  become: yes
  tasks:
  - name: Install git
    ansible.builtin.apt:
      name: git
      state: present
    tags: mygit
  - name: Install tree
    ansible.builtin.apt:
      name: tree
      state: present
    tags: mytree
  - name: Install wget
    ansible.builtin.apt:
      name: wget
      state: present
    tags: mywget
  