--- 
- hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Import VPC variable
    ansible.builtin.include_vars: vars/vpc-vars
  
  - name: Create VPC 
    amazon.aws.ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpcCidr }}"
      region: "{{ region }}"
      dns_hostnames: yes
      dns_support: yes
      tenancy: default
      state: "{{ state }}"
    register: vpc_output
  - ansible.builtin.debug: msg="{{ vpc_output.vpc.id }}"

  - name: Create Public Subnet 1 in zone1
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PubSub1Cidr }}"
      az: "{{ zone1 }}"
      map_public: yes
      tags:
        Name: PubSub1
    register: pub_sub1
  - ansible.builtin.debug: msg="{{ pub_sub1.subnet.id }}"
  - name: Create Public Subnet 2 in zone2
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PubSub2Cidr }}"
      az: "{{ zone2 }}"
      map_public: yes
      tags:
        Name: PubSub2
    register: pub_sub2
  - ansible.builtin.debug: msg="{{ pub_sub2.subnet.id }}"
  - name: Create Public Subnet 3 in zone3
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PubSub3Cidr }}"
      az: "{{ zone3 }}"
      map_public: yes
      tags:
        Name: PubSub3
    register: pub_sub3
  - ansible.builtin.debug: msg="{{ pub_sub3.subnet.id }}"

  - name: Create Private Subnet 1 in zone1
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PrivSub1Cidr }}"
      az: "{{ zone1 }}"
      tags:
        Name: PrivSub1
    register: priv_sub1
  - ansible.builtin.debug: msg="{{ priv_sub1.subnet.id }}"
  - name: Create Private Subnet 2 in zone2
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PrivSub2Cidr }}"
      az: "{{ zone2 }}"
      tags:
        Name: PrivSub2
    register: priv_sub2
  - ansible.builtin.debug: msg="{{ priv_sub2.subnet.id }}"
  - name: Create Private Subnet 3 in zone3
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PrivSub3Cidr }}"
      az: "{{ zone3 }}"
      tags:
        Name: PrivSub3
    register: priv_sub3
  - ansible.builtin.debug: msg="{{ priv_sub3.subnet.id }}"

  - name: Create Internet Gateway
    amazon.aws.ec2_vpc_igw:
      vpc_id: "{{ vpc_output.vpc.id }}"
      state: "{{ state }}"
      region: "{{ region }}"
      tags:
        Name: IGW
    register: igw_output
  - ansible.builtin.debug: msg="{{ igw_output.gateway_id }}"

  - name: Set up public subnet route table
    amazon.aws.ec2_vpc_route_table: 
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      tags:
        Name: PubRT
      subnets:
        - "{{ pub_sub1.subnet.id }}"
        - "{{ pub_sub2.subnet.id }}"
        - "{{ pub_sub3.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw_output.gateway_id }}"
    register: pub_rt_output
  - ansible.builtin.debug: msg="{{ pub_rt_output.route_table.id }}"

  - name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
    amazon.aws.ec2_vpc_nat_gateway:
      subnet_id: "{{ pub_sub1.subnet.id }}"
      wait: yes
      state: "{{ state }}"
      region: "{{ region }}"
      if_exist_do_not_create: yes
    register: nat_output
  - ansible.builtin.debug: msg="{{ nat_output }}"

  - name: Set up private subnet route table
    amazon.aws.ec2_vpc_route_table:
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      tags:
        Name: PrivRT
      subnets:
        - "{{ priv_sub1.subnet.id }}"
        - "{{ priv_sub2.subnet.id }}"
        - "{{ priv_sub3.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ nat_output.nat_gateway_id }}"
    register: priv_rt_output
  - ansible.builtin.debug: msg="{{ priv_rt_output.route_table.id }}"