--- 
- hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Import VPC variable
    ansible.builtin.include_vars: vars/vpc-vars
  
  - name: Create VPC 
    amazon.aws.ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpcCidr }}"
      region: "{{ region }}"
      dns_hostnames: yes
      dns_support: yes
      tenancy: default
      state: "{{ state }}"
    register: vpc_output
  - ansible.builtin.debug: msg="{{ vpc_output.vpc.id }}"

  - name: Create Public Subnet 1 in zone1
    amazon.aws.ec2_vpc_subnet:
      state: "{{ state }}"
      vpc_id: "{{ vpc_output.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ PubSub1Cidr }}"
      az: "{{ zone1 }}"
      map_public: yes
      tags:
        Name: PubSub1
    register: pub_sub1
  - ansible.builtin.debug: msg="{{ pub_sub1.subnet.id }}"
