--- 
- hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Import vpc variable files
    ansible.builtin.include_vars: vars/output_vars
  - name: Import vprofile setupvariable 
    ansible.builtin.include_vars: vars/vprostacksetup

  - name: create vprofile EC2 key pair 
    amazon.aws.ec2_key:
      name: vprokey
      region: "{{region}}"
    register: vprokey_out

  - name: store private key into file loginkey_vpro.pem
    copy:
      content: "{{vprokey_out.key.private_key}}"
      dest: ./loginkey_vpro.pem
      mode: 0600
    when: vprokey_out.changed
  