--- 
- name: Configure Apache web server 
  hosts: all 
  become: yes
  tasks: 
  - name: Install latest version of Apache 
    ansible.builtin.yum:
      name: httpd   
      state: latest
  - name: Start Apache server
    ansible.builtin.service:
      name: httpd
      state: started