--- 
- name: Check nexus folder stat
  ansible.builtin.stat:
    path: /opt/nexus 
  register: stat_result
- ansible.builtin.debug: msg="{{ stat_result.stat.exists }}"

- name: Download Nexus
  aansible.builtin.get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /opt/ 
  register: download_result
- ansible.builtin.debug: msg="{{ download_result.dest }}"

- name: Untar Nexus Installer 
  ansible.builtin.unarchive:
    src: "{{ download_result.dest }}"
    dest: /opt/
    remote_src: yes
  when: not stat_result.stat.exists

- name: Find nexus folder 
  ansible.builtin.find:
    path: /opt/
    patterns: "nexus-*"
    file_type: directory
  register: find_result
- ansible.builtin.debug: msg="{{ find_result }}"

- name: Rename nexus folder
  ansible.builtin.shell: mv {{ find_result.files[0].path }} /opt/nexus
  when: not stat_result.stat.exists
